import type { Metadata } from 'next'
import { Geist, Geist_Mono, Delius_Swash_Caps, Teko } from 'next/font/google'
import './globals.css'

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const deliusSwash = Delius_Swash_Caps({
  variable: '--font-delius-swash',
  weight: '400',
})

const kalam = Teko({
  variable: '--font-kalam',
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${deliusSwash.variable} ${kalam.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
